// <auto-generated />
using System;
using EiVae.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EiVae.Infrastructure.Migrations
{
    [DbContext(typeof(VaeDbContext))]
    [Migration("20260919141030_EvolutionsOperationnelles")]
    partial class EvolutionsOperationnelles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EiVae.Domain.Entities.AlerteInstance", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CodeRegle")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Detail")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("DetecteeLe")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MotifReport")
                        .HasColumnType("text");

                    b.Property<int>("ParcoursId")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("ReporteeJusquA")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset?>("ResolueLe")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Severite")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ResolueLe");

                    b.HasIndex("ParcoursId", "CodeRegle", "ResolueLe");

                    b.ToTable("alertes", (string)null);
                });

            modelBuilder.Entity("EiVae.Domain.Entities.AtelierCollectif", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CohorteId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<decimal>("DureeHeures")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<int?>("IntervenantId")
                        .HasColumnType("integer");

                    b.Property<string>("Modalite")
                        .HasColumnType("text");

                    b.Property<bool>("Realise")
                        .HasColumnType("boolean");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("UrlEmargement")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CohorteId");

                    b.HasIndex("IntervenantId");

                    b.ToTable("ateliers_collectifs", (string)null);
                });

            modelBuilder.Entity("EiVae.Domain.Entities.BlocCompetences", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CertificationId")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Competences")
                        .HasColumnType("text");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("ModalitesEvaluation")
                        .HasColumnType("text");

                    b.Property<int>("Ordre")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CertificationId", "Code")
                        .IsUnique();

                    b.ToTable("blocs_competences", (string)null);
                });

            modelBuilder.Entity("EiVae.Domain.Entities.Candidat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CodePostal")
                        .HasColumnType("text");

                    b.Property<bool>("ConsentementRgpd")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("CreeLe")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DateConsentementRgpd")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DateNaissance")
                        .HasColumnType("date");

                    b.Property<string>("Departement")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("IdentifiantFranceVae")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("ModifieLe")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("Region")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Telephone")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Ville")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("IdentifiantFranceVae")
                        .IsUnique()
                        .HasFilter("\"IdentifiantFranceVae\" IS NOT NULL");

                    b.HasIndex("Nom", "Prenom");

                    b.ToTable("candidats", (string)null);
                });

            modelBuilder.Entity("EiVae.Domain.Entities.Certificateur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactEmail")
                        .HasColumnType("text");

                    b.Property<string>("ContactTelephone")
                        .HasColumnType("text");

                    b.Property<string>("Etat")
                        .HasColumnType("text");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Siret")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Siret")
                        .IsUnique()
                        .HasFilter("\"Siret\" IS NOT NULL");

                    b.ToTable("certificateurs", (string)null);
                });

            modelBuilder.Entity("EiVae.Domain.Entities.Certification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Abrege")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<bool>("ActifFranceCompetences")
                        .HasColumnType("boolean");

                    b.Property<string>("ActivitesVisees")
                        .HasColumnType("text");

                    b.Property<string>("CapacitesAttestees")
                        .HasColumnType("text");

                    b.Property<string>("CodeRncp")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("CodesNsfJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("CodesRomeJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("CompositionJuryVae")
                        .HasColumnType("text");

                    b.Property<string>("ContactCertificateurEmail")
                        .HasColumnType("text");

                    b.Property<string>("ContactCertificateurNom")
                        .HasColumnType("text");

                    b.Property<string>("ContactCertificateurTelephone")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreeLe")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DateDecision")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DateDerniereModificationFiche")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DateFinEnregistrement")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DateLimiteDelivrance")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset?>("DerniereSynchronisation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DomaineEi")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int?>("DureeHabituelleJours")
                        .HasColumnType("integer");

                    b.Property<string>("EtatFiche")
                        .HasColumnType("text");

                    b.Property<string>("FormacodesJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("IdFiche")
                        .HasColumnType("text");

                    b.Property<string>("Intitule")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("LibelleNiveau")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ModifieLe")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Niveau")
                        .HasColumnType("integer");

                    b.Property<string>("ObjectifsContexte")
                        .HasColumnType("text");

                    b.Property<string>("Particularites")
                        .HasColumnType("text");

                    b.Property<string>("Prerequis")
                        .HasColumnType("text");

                    b.Property<string>("ReglementationActivites")
                        .HasColumnType("text");

                    b.Property<string>("SecteursActivite")
                        .HasColumnType("text");

                    b.Property<string>("StatistiquesJson")
                        .HasColumnType("jsonb");

                    b.Property<int>("StatutInterne")
                        .HasColumnType("integer");

                    b.Property<string>("TypeEmploiAccessibles")
                        .HasColumnType("text");

                    b.Property<string>("TypeEnregistrement")
                        .HasColumnType("text");

                    b.Property<bool>("VoieApprentissage")
                        .HasColumnType("boolean");

                    b.Property<bool>("VoieCandidatLibre")
                        .HasColumnType("boolean");

                    b.Property<bool>("VoieContratProfessionnalisation")
                        .HasColumnType("boolean");

                    b.Property<bool>("VoieFormationContinue")
                        .HasColumnType("boolean");

                    b.Property<bool>("VoieFormationInitiale")
                        .HasColumnType("boolean");

                    b.Property<bool>("VoieVaeOuverte")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("CodeRncp")
                        .IsUnique();

                    b.HasIndex("DomaineEi");

                    b.ToTable("certifications", (string)null);
                });

            modelBuilder.Entity("EiVae.Domain.Entities.CertificationCertificateur", b =>
                {
                    b.Property<int>("CertificationId")
                        .HasColumnType("integer");

                    b.Property<int>("CertificateurId")
                        .HasColumnType("integer");

                    b.Property<bool>("EstPrincipal")
                        .HasColumnType("boolean");

                    b.HasKey("CertificationId", "CertificateurId");

                    b.HasIndex("CertificateurId");

                    b.ToTable("certification_certificateurs", (string)null);
                });

            modelBuilder.Entity("EiVae.Domain.Entities.CertificationModule", b =>
                {
                    b.Property<int>("CertificationId")
                        .HasColumnType("integer");

                    b.Property<int>("ModuleAcademieId")
                        .HasColumnType("integer");

                    b.Property<bool>("Obligatoire")
                        .HasColumnType("boolean");

                    b.HasKey("CertificationId", "ModuleAcademieId");

                    b.HasIndex("ModuleAcademieId");

                    b.ToTable("certification_modules", (string)null);
                });

            modelBuilder.Entity("EiVae.Domain.Entities.Cohorte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AnimateurId")
                        .HasColumnType("integer");

                    b.Property<int?>("CertificationId")
                        .HasColumnType("integer");

                    b.Property<string>("Commentaire")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreeLe")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DateCloturePrevue")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DateOuverture")
                        .HasColumnType("date");

                    b.Property<int?>("EffectifCible")
                        .HasColumnType("integer");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("ProjetCollectifId")
                        .HasColumnType("integer");

                    b.Property<string>("Rythme")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AnimateurId");

                    b.HasIndex("CertificationId");

                    b.HasIndex("ProjetCollectifId");

                    b.ToTable("cohortes", (string)null);
                });

            modelBuilder.Entity("EiVae.Domain.Entities.DemandeWeb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CertificationSouhaitee")
                        .HasColumnType("text");

                    b.Property<string>("CodePostal")
                        .HasColumnType("text");

                    b.Property<string>("CodeRncpDetecte")
                        .HasColumnType("text");

                    b.Property<string>("CommentaireTraitement")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<int?>("ParcoursCreeId")
                        .HasColumnType("integer");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTimeOffset>("RecueLe")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Source")
                        .HasColumnType("text");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Telephone")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("TraiteeLe")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TraiteePar")
                        .HasColumnType("text");

                    b.Property<string>("Ville")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RecueLe");

                    b.HasIndex("Statut");

                    b.ToTable("demandes_web", (string)null);
                });

            modelBuilder.Entity("EiVae.Domain.Entities.Facture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CodeAcf")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Commentaire")
                        .HasColumnType("text");

                    b.Property<DateOnly>("DateEmission")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DateReglement")
                        .HasColumnType("date");

                    b.Property<string>("Financeur")
                        .HasColumnType("text");

                    b.Property<decimal>("MontantHt")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<int>("ParcoursId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Numero")
                        .IsUnique();

                    b.HasIndex("ParcoursId");

                    b.ToTable("factures", (string)null);
                });

            modelBuilder.Entity("EiVae.Domain.Entities.Financement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Commentaire")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("DateDemande")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DateSecurisation")
                        .HasColumnType("date");

                    b.Property<int>("Dispositif")
                        .HasColumnType("integer");

                    b.Property<string>("Financeur")
                        .HasColumnType("text");

                    b.Property<decimal?>("MontantAccorde")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("NumeroPriseEnCharge")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("ParcoursId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("ResteACharge")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("ParcoursId");

                    b.ToTable("financements", (string)null);
                });

            modelBuilder.Entity("EiVae.Domain.Entities.GrilleTarifaire", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("CoutHoraireArchitecte")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("CoutHoraireIntervenant")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<DateOnly>("DateEffet")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DateFin")
                        .HasColumnType("date");

                    b.Property<decimal>("ForfaitArchitecture")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("FraisJury")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("HeuresArchitectureParDossier")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("PlafondHeuresCollectif")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("PlafondHeuresComplementFormatif")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("PlafondHeuresIndividuel")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("PlafondMontantTotal")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("TarifHoraireCollectif")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("TarifHoraireComplementFormatif")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("TarifHoraireIndividuel")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("DateEffet");

                    b.ToTable("grilles_tarifaires", (string)null);
                });

            modelBuilder.Entity("EiVae.Domain.Entities.HabilitationIntervenant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CertificationId")
                        .HasColumnType("integer");

                    b.Property<string>("Commentaire")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("DateHabilitation")
                        .HasColumnType("date");

                    b.Property<int>("IntervenantId")
                        .HasColumnType("integer");

                    b.Property<string>("Niveau")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("Id");

                    b.HasIndex("CertificationId");

                    b.HasIndex("IntervenantId", "CertificationId")
                        .IsUnique();

                    b.ToTable("habilitations", (string)null);
                });

            modelBuilder.Entity("EiVae.Domain.Entities.HistoriqueStatut", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Auteur")
                        .HasColumnType("text");

                    b.Property<string>("Commentaire")
                        .HasColumnType("text");

                    b.Property<int>("EtapeNouvelle")
                        .HasColumnType("integer");

                    b.Property<int?>("EtapePrecedente")
                        .HasColumnType("integer");

                    b.Property<int>("ParcoursId")
                        .HasColumnType("integer");

                    b.Property<int>("StatutSecondaire")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("SurvenuLe")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ParcoursId", "SurvenuLe");

                    b.ToTable("historique_statuts", (string)null);
                });

            modelBuilder.Entity("EiVae.Domain.Entities.ImportRun", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Declencheur")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("DemarreLe")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Journal")
                        .HasColumnType("text");

                    b.Property<int>("NombreCrees")
                        .HasColumnType("integer");

                    b.Property<int>("NombreErreurs")
                        .HasColumnType("integer");

                    b.Property<int>("NombreIgnores")
                        .HasColumnType("integer");

                    b.Property<int>("NombreLus")
                        .HasColumnType("integer");

                    b.Property<int>("NombreMisAJour")
                        .HasColumnType("integer");

                    b.Property<string>("Reference")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<int>("Statut")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("TermineLe")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Source", "DemarreLe");

                    b.ToTable("imports", (string)null);
                });

            modelBuilder.Entity("EiVae.Domain.Entities.Intervenant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CapaciteCandidats")
                        .HasColumnType("integer");

                    b.Property<decimal?>("CapaciteHeuresTrimestre")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.Property<DateTimeOffset>("CreeLe")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DateEntreeReseau")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DateSortieReseau")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<bool>("InterventionDistanciel")
                        .HasColumnType("boolean");

                    b.Property<bool>("InterventionPresentiel")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("ModifieLe")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Prenom")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("Region")
                        .HasColumnType("text");

                    b.Property<string>("SharePointDossier")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Siret")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Specialites")
                        .HasColumnType("text");

                    b.Property<int>("Statut")
                        .HasColumnType("integer");

                    b.Property<decimal?>("TarifHoraire")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.Property<string>("Telephone")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Territoire")
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Type");

                    b.HasIndex("Nom", "Prenom");

                    b.ToTable("intervenants", (string)null);
                });

            modelBuilder.Entity("EiVae.Domain.Entities.JournalAudit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("AncienneValeur")
                        .HasColumnType("text");

                    b.Property<string>("Auteur")
                        .HasColumnType("text");

                    b.Property<string>("Champ")
                        .HasColumnType("text");

                    b.Property<string>("Entite")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("EntiteId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("NouvelleValeur")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("SurvenuLe")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SurvenuLe");

                    b.HasIndex("Entite", "EntiteId");

                    b.ToTable("journal_audit", (string)null);
                });

            modelBuilder.Entity("EiVae.Domain.Entities.ModuleAcademie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Actif")
                        .HasColumnType("boolean");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<decimal?>("DureeHeures")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("modules_academie", (string)null);
                });

            modelBuilder.Entity("EiVae.Domain.Entities.Notification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreeLe")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DestinataireEmail")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("DestinataireNom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("EmailEnvoyeLe")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErreurEmail")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("Evenement")
                        .HasColumnType("integer");

                    b.Property<int?>("IntervenantId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("LueLe")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int?>("ParcoursId")
                        .HasColumnType("integer");

                    b.Property<int?>("RoleAccesId")
                        .HasColumnType("integer");

                    b.Property<int>("TentativesEmail")
                        .HasColumnType("integer");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("UtilisateurId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreeLe");

                    b.HasIndex("LueLe");

                    b.HasIndex("ParcoursId", "Evenement");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("EiVae.Domain.Entities.ParametreGestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Categorie")
                        .HasColumnType("text");

                    b.Property<string>("Cle")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("ModifieLe")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiePar")
                        .HasColumnType("text");

                    b.Property<string>("Unite")
                        .HasColumnType("text");

                    b.Property<string>("Valeur")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Cle")
                        .IsUnique();

                    b.ToTable("parametres_gestion", (string)null);
                });

            modelBuilder.Entity("EiVae.Domain.Entities.Parcours", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AapId")
                        .HasColumnType("integer");

                    b.Property<int?>("AccompagnateurId")
                        .HasColumnType("integer");

                    b.Property<string>("BlocsValidesJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("BlocsVisesJson")
                        .HasColumnType("jsonb");

                    b.Property<int>("CandidatId")
                        .HasColumnType("integer");

                    b.Property<string>("CandidatureFranceVaeId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int?>("CertificationId")
                        .HasColumnType("integer");

                    b.Property<string>("CodeAcfSolei")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int?>("CohorteId")
                        .HasColumnType("integer");

                    b.Property<string>("CommentaireJury")
                        .HasColumnType("text");

                    b.Property<string>("CommentaireSortie")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreeLe")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DateDebutAccompagnement")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DateDebutParcours")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DateDemande")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DateDepotDossierValidation")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DateDepotFaisabilite")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DateDernierMouvement")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DateDerniereActiviteAcademie")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DateEntretienPostJury")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DateJury")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DateParcoursValide")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DatePremierContact")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DateRdvFaisabilite")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DateRecevabilite")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DateRecueilBesoins")
                        .HasColumnType("date");

                    b.Property<bool>("EspaceAcademieCree")
                        .HasColumnType("boolean");

                    b.Property<int>("Etape")
                        .HasColumnType("integer");

                    b.Property<bool>("ForfaitArchitectureApplique")
                        .HasColumnType("boolean");

                    b.Property<bool>("FraisJuryInclus")
                        .HasColumnType("boolean");

                    b.Property<int?>("GestionnaireId")
                        .HasColumnType("integer");

                    b.Property<int?>("GrilleTarifaireId")
                        .HasColumnType("integer");

                    b.Property<decimal>("HeuresCollectifPrescrites")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.Property<decimal>("HeuresComplementFormatifPrescrites")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.Property<decimal>("HeuresIndividuelPrescrites")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.Property<string>("Historique")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ModifieLe")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MotifSortie")
                        .HasColumnType("integer");

                    b.Property<int>("Origine")
                        .HasColumnType("integer");

                    b.Property<int>("ResultatJury")
                        .HasColumnType("integer");

                    b.Property<string>("SharePointDossier")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("StatutSecondaire")
                        .HasColumnType("integer");

                    b.Property<string>("UrlEspaceAcademie")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AapId");

                    b.HasIndex("AccompagnateurId");

                    b.HasIndex("CandidatId");

                    b.HasIndex("CandidatureFranceVaeId")
                        .IsUnique()
                        .HasFilter("\"CandidatureFranceVaeId\" IS NOT NULL");

                    b.HasIndex("CertificationId");

                    b.HasIndex("CohorteId");

                    b.HasIndex("DateDebutParcours");

                    b.HasIndex("DateDernierMouvement");

                    b.HasIndex("Etape");

                    b.HasIndex("GestionnaireId");

                    b.HasIndex("GrilleTarifaireId");

                    b.ToTable("parcours", (string)null);
                });

            modelBuilder.Entity("EiVae.Domain.Entities.PieceDossier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CheminSharePoint")
                        .HasColumnType("text");

                    b.Property<string>("Commentaire")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("DateDepot")
                        .HasColumnType("date");

                    b.Property<int>("ExigibleAPartirDe")
                        .HasColumnType("integer");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("Obligatoire")
                        .HasColumnType("boolean");

                    b.Property<int>("ParcoursId")
                        .HasColumnType("integer");

                    b.Property<bool>("Presente")
                        .HasColumnType("boolean");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("Id");

                    b.HasIndex("ParcoursId");

                    b.ToTable("pieces_dossier", (string)null);
                });

            modelBuilder.Entity("EiVae.Domain.Entities.ProjetCollectif", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AapReferentId")
                        .HasColumnType("integer");

                    b.Property<string>("Commentaire")
                        .HasColumnType("text");

                    b.Property<string>("ConventionCollective")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreeLe")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DateCloture")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DateCloturePrevue")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DateContractualisation")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DateDiagnostic")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DateOuverture")
                        .HasColumnType("date");

                    b.Property<int>("Dispositif")
                        .HasColumnType("integer");

                    b.Property<int?>("Effectif")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("ModifieLe")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("MontantContractualise")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Opco")
                        .HasColumnType("text");

                    b.Property<string>("RaisonSociale")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("ReferenceContrat")
                        .HasColumnType("text");

                    b.Property<string>("ReferentEmail")
                        .HasColumnType("text");

                    b.Property<string>("ReferentFonction")
                        .HasColumnType("text");

                    b.Property<string>("ReferentNom")
                        .HasColumnType("text");

                    b.Property<string>("ReferentTelephone")
                        .HasColumnType("text");

                    b.Property<string>("SecteurActivite")
                        .HasColumnType("text");

                    b.Property<string>("SharePointDossier")
                        .HasColumnType("text");

                    b.Property<string>("Siret")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("Id");

                    b.HasIndex("AapReferentId");

                    b.ToTable("projets_collectifs", (string)null);
                });

            modelBuilder.Entity("EiVae.Domain.Entities.RegleAlerte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Acteur")
                        .HasColumnType("integer");

                    b.Property<string>("ActionAttendue")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("Condition")
                        .HasColumnType("integer");

                    b.Property<int?>("EtapeMax")
                        .HasColumnType("integer");

                    b.Property<int?>("EtapeMin")
                        .HasColumnType("integer");

                    b.Property<string>("Fondement")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("JalonAttendu")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("JalonReference")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<bool>("JoursOuvres")
                        .HasColumnType("boolean");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("ModifieLe")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Ordre")
                        .HasColumnType("integer");

                    b.Property<string>("Responsable")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int?>("Seuil")
                        .HasColumnType("integer");

                    b.Property<int?>("SeuilMax")
                        .HasColumnType("integer");

                    b.Property<int>("Severite")
                        .HasColumnType("integer");

                    b.Property<int?>("Statut")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("regles_alertes", (string)null);
                });

            modelBuilder.Entity("EiVae.Domain.Entities.RoleAcces", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("DroitsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("NotificationsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("Ordre")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Nom")
                        .IsUnique();

                    b.ToTable("roles_acces", (string)null);
                });

            modelBuilder.Entity("EiVae.Domain.Entities.Seance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Commentaire")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreeLe")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<decimal>("DureeHeures")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<bool>("Emargee")
                        .HasColumnType("boolean");

                    b.Property<int?>("IntervenantId")
                        .HasColumnType("integer");

                    b.Property<string>("Modalite")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<int>("Nature")
                        .HasColumnType("integer");

                    b.Property<string>("Objet")
                        .HasColumnType("text");

                    b.Property<int>("ParcoursId")
                        .HasColumnType("integer");

                    b.Property<bool>("Realisee")
                        .HasColumnType("boolean");

                    b.Property<string>("UrlEmargement")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IntervenantId");

                    b.HasIndex("ParcoursId", "Date");

                    b.ToTable("seances", (string)null);
                });

            modelBuilder.Entity("EiVae.Domain.Entities.Utilisateur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Actif")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("CreeLe")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DerniereConnexion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<int?>("IntervenantId")
                        .HasColumnType("integer");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("Prenom")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<int?>("RoleAccesId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("IntervenantId");

                    b.HasIndex("RoleAccesId");

                    b.ToTable("utilisateurs", (string)null);
                });

            modelBuilder.Entity("EiVae.Domain.Entities.AlerteInstance", b =>
                {
                    b.HasOne("EiVae.Domain.Entities.Parcours", "Parcours")
                        .WithMany("Alertes")
                        .HasForeignKey("ParcoursId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parcours");
                });

            modelBuilder.Entity("EiVae.Domain.Entities.AtelierCollectif", b =>
                {
                    b.HasOne("EiVae.Domain.Entities.Cohorte", "Cohorte")
                        .WithMany("Ateliers")
                        .HasForeignKey("CohorteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EiVae.Domain.Entities.Intervenant", "Intervenant")
                        .WithMany()
                        .HasForeignKey("IntervenantId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Cohorte");

                    b.Navigation("Intervenant");
                });

            modelBuilder.Entity("EiVae.Domain.Entities.BlocCompetences", b =>
                {
                    b.HasOne("EiVae.Domain.Entities.Certification", "Certification")
                        .WithMany("Blocs")
                        .HasForeignKey("CertificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Certification");
                });

            modelBuilder.Entity("EiVae.Domain.Entities.CertificationCertificateur", b =>
                {
                    b.HasOne("EiVae.Domain.Entities.Certificateur", "Certificateur")
                        .WithMany("Certifications")
                        .HasForeignKey("CertificateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EiVae.Domain.Entities.Certification", "Certification")
                        .WithMany("Certificateurs")
                        .HasForeignKey("CertificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Certificateur");

                    b.Navigation("Certification");
                });

            modelBuilder.Entity("EiVae.Domain.Entities.CertificationModule", b =>
                {
                    b.HasOne("EiVae.Domain.Entities.Certification", "Certification")
                        .WithMany("Modules")
                        .HasForeignKey("CertificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EiVae.Domain.Entities.ModuleAcademie", "ModuleAcademie")
                        .WithMany("Certifications")
                        .HasForeignKey("ModuleAcademieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Certification");

                    b.Navigation("ModuleAcademie");
                });

            modelBuilder.Entity("EiVae.Domain.Entities.Cohorte", b =>
                {
                    b.HasOne("EiVae.Domain.Entities.Intervenant", "Animateur")
                        .WithMany()
                        .HasForeignKey("AnimateurId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EiVae.Domain.Entities.Certification", "Certification")
                        .WithMany()
                        .HasForeignKey("CertificationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EiVae.Domain.Entities.ProjetCollectif", "ProjetCollectif")
                        .WithMany("Cohortes")
                        .HasForeignKey("ProjetCollectifId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Animateur");

                    b.Navigation("Certification");

                    b.Navigation("ProjetCollectif");
                });

            modelBuilder.Entity("EiVae.Domain.Entities.Facture", b =>
                {
                    b.HasOne("EiVae.Domain.Entities.Parcours", "Parcours")
                        .WithMany("Factures")
                        .HasForeignKey("ParcoursId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parcours");
                });

            modelBuilder.Entity("EiVae.Domain.Entities.Financement", b =>
                {
                    b.HasOne("EiVae.Domain.Entities.Parcours", "Parcours")
                        .WithMany("Financements")
                        .HasForeignKey("ParcoursId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parcours");
                });

            modelBuilder.Entity("EiVae.Domain.Entities.HabilitationIntervenant", b =>
                {
                    b.HasOne("EiVae.Domain.Entities.Certification", "Certification")
                        .WithMany("Habilitations")
                        .HasForeignKey("CertificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EiVae.Domain.Entities.Intervenant", "Intervenant")
                        .WithMany("Habilitations")
                        .HasForeignKey("IntervenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Certification");

                    b.Navigation("Intervenant");
                });

            modelBuilder.Entity("EiVae.Domain.Entities.HistoriqueStatut", b =>
                {
                    b.HasOne("EiVae.Domain.Entities.Parcours", "Parcours")
                        .WithMany("HistoriqueStatuts")
                        .HasForeignKey("ParcoursId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parcours");
                });

            modelBuilder.Entity("EiVae.Domain.Entities.Notification", b =>
                {
                    b.HasOne("EiVae.Domain.Entities.Parcours", "Parcours")
                        .WithMany()
                        .HasForeignKey("ParcoursId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Parcours");
                });

            modelBuilder.Entity("EiVae.Domain.Entities.Parcours", b =>
                {
                    b.HasOne("EiVae.Domain.Entities.Intervenant", "Aap")
                        .WithMany()
                        .HasForeignKey("AapId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EiVae.Domain.Entities.Intervenant", "Accompagnateur")
                        .WithMany()
                        .HasForeignKey("AccompagnateurId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EiVae.Domain.Entities.Candidat", "Candidat")
                        .WithMany("Parcours")
                        .HasForeignKey("CandidatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EiVae.Domain.Entities.Certification", "Certification")
                        .WithMany("Parcours")
                        .HasForeignKey("CertificationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EiVae.Domain.Entities.Cohorte", "Cohorte")
                        .WithMany("Parcours")
                        .HasForeignKey("CohorteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EiVae.Domain.Entities.Intervenant", "Gestionnaire")
                        .WithMany()
                        .HasForeignKey("GestionnaireId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EiVae.Domain.Entities.GrilleTarifaire", "GrilleTarifaire")
                        .WithMany()
                        .HasForeignKey("GrilleTarifaireId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Aap");

                    b.Navigation("Accompagnateur");

                    b.Navigation("Candidat");

                    b.Navigation("Certification");

                    b.Navigation("Cohorte");

                    b.Navigation("Gestionnaire");

                    b.Navigation("GrilleTarifaire");
                });

            modelBuilder.Entity("EiVae.Domain.Entities.PieceDossier", b =>
                {
                    b.HasOne("EiVae.Domain.Entities.Parcours", "Parcours")
                        .WithMany("Pieces")
                        .HasForeignKey("ParcoursId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parcours");
                });

            modelBuilder.Entity("EiVae.Domain.Entities.ProjetCollectif", b =>
                {
                    b.HasOne("EiVae.Domain.Entities.Intervenant", "AapReferent")
                        .WithMany()
                        .HasForeignKey("AapReferentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AapReferent");
                });

            modelBuilder.Entity("EiVae.Domain.Entities.Seance", b =>
                {
                    b.HasOne("EiVae.Domain.Entities.Intervenant", "Intervenant")
                        .WithMany("Seances")
                        .HasForeignKey("IntervenantId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EiVae.Domain.Entities.Parcours", "Parcours")
                        .WithMany("Seances")
                        .HasForeignKey("ParcoursId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Intervenant");

                    b.Navigation("Parcours");
                });

            modelBuilder.Entity("EiVae.Domain.Entities.Utilisateur", b =>
                {
                    b.HasOne("EiVae.Domain.Entities.Intervenant", "Intervenant")
                        .WithMany()
                        .HasForeignKey("IntervenantId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EiVae.Domain.Entities.RoleAcces", "RoleAcces")
                        .WithMany("Utilisateurs")
                        .HasForeignKey("RoleAccesId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Intervenant");

                    b.Navigation("RoleAcces");
                });

            modelBuilder.Entity("EiVae.Domain.Entities.Candidat", b =>
                {
                    b.Navigation("Parcours");
                });

            modelBuilder.Entity("EiVae.Domain.Entities.Certificateur", b =>
                {
                    b.Navigation("Certifications");
                });

            modelBuilder.Entity("EiVae.Domain.Entities.Certification", b =>
                {
                    b.Navigation("Blocs");

                    b.Navigation("Certificateurs");

                    b.Navigation("Habilitations");

                    b.Navigation("Modules");

                    b.Navigation("Parcours");
                });

            modelBuilder.Entity("EiVae.Domain.Entities.Cohorte", b =>
                {
                    b.Navigation("Ateliers");

                    b.Navigation("Parcours");
                });

            modelBuilder.Entity("EiVae.Domain.Entities.Intervenant", b =>
                {
                    b.Navigation("Habilitations");

                    b.Navigation("Seances");
                });

            modelBuilder.Entity("EiVae.Domain.Entities.ModuleAcademie", b =>
                {
                    b.Navigation("Certifications");
                });

            modelBuilder.Entity("EiVae.Domain.Entities.Parcours", b =>
                {
                    b.Navigation("Alertes");

                    b.Navigation("Factures");

                    b.Navigation("Financements");

                    b.Navigation("HistoriqueStatuts");

                    b.Navigation("Pieces");

                    b.Navigation("Seances");
                });

            modelBuilder.Entity("EiVae.Domain.Entities.ProjetCollectif", b =>
                {
                    b.Navigation("Cohortes");
                });

            modelBuilder.Entity("EiVae.Domain.Entities.RoleAcces", b =>
                {
                    b.Navigation("Utilisateurs");
                });
#pragma warning restore 612, 618
        }
    }
}
